version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/services/auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/services/messaging"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/services/profiles"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"