apiVersion: v1
kind: ConfigMap
metadata:
  name: profiles-config
  namespace: chat-app
data:
  PORT: {{ .Values.env.PORT | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  AUTH_SERVICE_URL: {{ .Values.env.AUTH_SERVICE_URL | quote }}
