apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: profiles-monitor
  namespace: chat-app
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: profiles
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
