# ConfigMap Messaging : variables non sensibles
# DATABASE_URL et RABBITMQ_URL sont dans app-secrets.
apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-config
  namespace: chat-app
data:
  PORT: "3003"
  REDIS_URL: "redis://redis:6379"
  AUTH_SERVICE_URL: "http://auth:3001"
