replicaCount: 1

image:
  repository: badrkhafif98/chat-auth
  tag: latest
  pullPolicy: Never

service:
  port: 3001

env:
  PORT: "3001"
  DATABASE_URL: "postgresql://user:password@postgres:5432/chat_db"
  REDIS_URL: "redis://redis:6379"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"

secrets:
  JWT_SECRET: ""
  JWT_REFRESH_SECRET: ""

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"