# Deployment RabbitMQ pour la messagerie événementielle
# Port 5672 (AMQP), 15672 (interface management)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: password
