replicaCount: 1

image:
  repository: badrkhafif98/chat-front
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
