sonar.projectKey=chat-app_profiles
sonar.projectName=Chat App - Profiles Service
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**