sonar.projectKey=chat-app_messaging
sonar.projectName=Chat App - Messaging Service
sonar.sources=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**
sonar.host.url=https://sonarcloud.io
sonar.organization=griffith-0-0