apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: chat-app
data:
  PORT: {{ .Values.env.PORT | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}
  JWT_EXPIRES_IN: {{ .Values.env.JWT_EXPIRES_IN | quote }}
  JWT_REFRESH_EXPIRES_IN: {{ .Values.env.JWT_REFRESH_EXPIRES_IN | quote }}