apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: chat-app
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.JWT_REFRESH_SECRET | b64enc | quote }}