# ConfigMap Profiles : variables non sensibles
# DATABASE_URL est dans app-secrets.
apiVersion: v1
kind: ConfigMap
metadata:
  name: profiles-config
  namespace: chat-app
data:
  PORT: "3002"
  AUTH_SERVICE_URL: "http://auth:3001"
